# Server Configuration
server:
  port: 8080

# Origin Configuration
origins:
  - name: Server1
    edge: /server1
    url: "https://api.sampleapis.com/avatar/info"
  - name: Server2
    edge: /server2
    url: "https://api.sampleapis.com/beers/ale"
  - name: Server3
    edge: /server3
    url: "https://api.sampleapis.com/csscolornames/colors"

# Rate Limiter Configuration
rl:
  enabled: true
  allowed: 5
  timeframe: 10
  block: 20

redis:
  url: kalkan-redis:6379 # Redis docker container URL
  password: "" # no password set
  db: 0 # use default DB
  expiration: 3600
